# Generated by Django 2.2 on 2020-11-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Reg_App', '0002_auto_20201111_1724'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='Login_Reg_App.User'),
        ),
    ]
