# Generated by Django 2.2 on 2020-11-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Reg_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagepost',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='MessagePost',
        ),
    ]
